name: Deploy Docker Build to gh-pages

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-app-image .

    - name: Create container from image
      run: |
        docker create --name mycontainer my-app-image

    - name: Copy build output from container
      run: |
        docker cp mycontainer:/usr/share/nginx/html ./build

    - name: Remove container
      run: docker rm mycontainer

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.PAGE_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
